# -*- coding: utf-8 -*-
"""Lab8 Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRTxnuV_oUrbyTHf3mELXqMZSc5qPRXJ
"""

#task3
def minimum_coins(coins, X):
    coin_list = [float('inf')] * (X + 1)
    coin_list[0] = 0

    for i in coins:
        for j in range(i, X + 1):
            coin_list[j] = min(coin_list[j], coin_list[j - i] + 1)

    if coin_list[X] != float('inf'):
      return coin_list[X]
    else:
      return -1

with open("/content/input3.txt", "r") as txt_input, open("/content/output3.txt", "w") as txt_output:

  N, X = map(int, txt_input.readline().split())
  variety = list(map(int, txt_input.readline().split()))
  #print(variety)
  result = minimum_coins(variety, X)
  print(result, file = txt_output)

txt_output.close()