# -*- coding: utf-8 -*-
"""Lab8 Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j1EO7D8g_GznHifPLJSSmh3JmA9Z7X5x
"""

#task2
def ways_of_climbing(N):
    if N <= 1:
        return 1

    steps = [0] * (N + 1)
    steps[0] = steps[1] = 1

    for i in range(2, N + 1):
        steps[i] = steps[i - 1] + steps[i - 2]

    return steps[N]


with open("/content/input2.txt", "r") as txt_input, open("/content/output2.txt", "w") as txt_output:
  N= int(txt_input.readline())
  result = ways_of_climbing(N)
  print(result, file = txt_output)

txt_output.close()