# -*- coding: utf-8 -*-
"""Task 1.A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vme3fJ18Vpwd6VUFmXQonnNGOB3J1JD1
"""

#Task 1.A

txt_input=open('/content/input1a.txt', 'r')
txt_output=open('/content/output1a.txt', 'w')
test_case = int(txt_input.readline())
print(test_case)

for i in range(test_case):
  num1 = txt_input.readline().strip()
  num = int(num1)
  if num % 2 == 0:
    print(num, "is an  Even number.", file = txt_output)
  else:
    print(num, "is an  Odd number.", file = txt_output)

txt_output.close()















