# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycSQIYuy9Y5qjunX0s4c3Sq0sj0PGpV-
"""

txt_input=open('/content/input3.txt', 'r')
txt_output=open('/content/output3.txt', 'w')
tot = int(txt_input.readline())
print(tot)

#tot = int(input())
merge=[]
if 1<= tot <= 1000:
  id = []
  mark= []
  id_in = txt_input.readline().split()
  for i in range(tot):
    id1 = int(id_in[i])
    id.append(id1)
  marks_in=txt_input.readline().split()
  for j in range(tot):
    mark1=int(marks_in[j])
    mark.append(mark1)
  for k in range(len(mark)):
    into = [id[k], mark[k]]
    merge.append(into)

for i in range(len(merge)-1 ):
  max = i
  for j in range(i+1, len(merge)):
    if merge[j][1] > merge[max][1]:
      max = j
    elif merge[j][1] == merge[max][1]:
      if merge[j][0] < merge[max][0]:
        max = j

  merge[i], merge[max] = merge[max], merge[i]
    
for i in range(len(merge)):
  print(f"ID: {merge[i][0]} Mark: {merge[i][1]}", file = txt_output)

txt_output.close()