# -*- coding: utf-8 -*-
"""Task 1.B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19wK4DJeLMWFiShIDOLzltsgKmXhEW3hj
"""

#Task 1.B

txt_input=open('/content/input1b.txt', 'r')
txt_output=open('/content/output1b.txt', 'w')
test_case = int((txt_input.readline()))
print(test_case)

for test in range(test_case):
  test_case = ((txt_input.readline()))
  test_case = test_case[10:]
  func = test_case.split()
  num1 = func[0]
  num2 = func[2]
  sign = func[1]

  result = 0
  if sign == "+":
    result = int(num1) + int(num2)
  if sign == "-":
    result = int(num1) - int(num2)
  if sign == "*":
    result = int(num1) * int(num2)
  if sign == "/":
    result = int(num1) / int(num2)

  print(f"The result of {test_case} is {result}", file =txt_output )
txt_output.close()