# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vGgTj5Fq0G2PV5yZuTkmS7LZo_fNIWHu
"""

#Task 2

txt_input=open('/content/input2.txt', 'r')
txt_output=open('/content/output2.txt', 'w')
test_case = int(txt_input.readline())
print(test_case)

inp = txt_input.readline().split()
inp1 = []
for i in range(len(inp)):
  ip = int(inp[i])
  inp1.append(ip)

for i in range(len(inp1)-1):
  max = i
  for j in range(i+1, len(inp1)):
    if inp1[j] < inp1[max]:
      max = j
   
  inp1[i], inp1[max] = inp1[max], inp1[i]
               
print(inp1)
for i in range(len(inp1)):
  print(inp1[i], end = " ", file=txt_output)

txt_output.close()

