# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8fqOr8St8qI3k0yqDPCQg4rfrYTdLrW
"""

#Task 4

txt_input=open('/content/input4.txt', 'r')
txt_output=open('/content/output4.txt', 'w')
test_case = int(txt_input.readline())
print(test_case)

list1=[]
for i in range(1, test_case+1):
  inp =txt_input.readline().strip("\n")
  list1.append(inp)


for i in range(len(list1)):
  for j in range(0, len(list1)-i-1):
    list2 = list1[j].split(' ')
    list3 = list1[j+1].split(' ')
    if list2[0] > list3[0]:
      list1[j], list1[j+1] = list1[j+1], list1[j]

    elif list2[0] == list3[0] and list2[-1] < list3[-1]:
      list1[j], list1[j+1] = list1[j+1], list1[j]

for i in list1:
  print(i, file = txt_output)

txt_output.close()