# -*- coding: utf-8 -*-
"""Lab 4 Task 1.a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GpvgJtyr8KyySxMp8dBroZtnEz0Kc1Sh
"""

txt_input=open('/content/input1.a.txt','r')
txt_output=open('/content/output1.a.txt','w')
test=txt_input.readline().split()
r = int(test[0])
c = int(test[1])
a=[[0]*(r+1) for i in range(r+1)]
b=[]
for i in range(c):
  b.append([int(i) for i in txt_input.readline().split()])
print(b)

for i in b:
  m, n, l = i
  a[m][n] = l
for i in a:
  print(i)
  print(' '.join([str(j) for j in i]), file=txt_output)

txt_output.close()