# -*- coding: utf-8 -*-
"""Lab 4 Task 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eu1K3dGTm0xuGsPEbvB4Np6s_cFHyYnL
"""

txt_input = open("/content/input6.txt", "r")
txt_output = open("/content/output6.txt", "w")
R, H = map(int, txt_input.readline().rstrip().split())
List1 = []
for x in txt_input:
    List1.append([i for i in x.rstrip()])

def DFS_Traversal(G, v):
    global H, R
    if G<0 or G>=R or v<0 or v>=H:
        return
    elif List1[G][v] == '#':
        return
    else:
        if List1[G][v] == 'D':
            global Dm
            Dm+=1
        List1[G][v] = '#'
        DFS_Traversal(G+1, v)
        DFS_Traversal(G-1, v)
        DFS_Traversal(G, v+1)
        DFS_Traversal(G, v-1)


def find_diamond():
    global R, H, Dm
    diamondcount = []
    for i in range(R):
        for j in range(H):
            Dm = 0
            if List1[i][j] != "#":
                DFS_Traversal(i, j)
                diamondcount.append(Dm)
    return diamondcount

maxDm = max(find_diamond())

print((str(maxDm)), file = txt_output)
txt_output.close()