# -*- coding: utf-8 -*-
"""Lab 4 Task 1.b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ub8qFP1CRKeP_aQSqyH60mktfhb_vi7f
"""

txt_input=open('/content/input1.b.txt','r')
txt_output=open('/content/output1.b.txt','w')
V,E= map(int, txt_input.readline().split())
List1 =[[]for i in range(0, V+1)]

for i in range(E):
  m, n, l = map(int, txt_input.readline().split())
  List1[m].append(tuple((n,l)))

for i in range(len(List1)):
  j = List1[i]
  txt_output.write(f"{i} :")
  for k,l in j:
    txt_output.write(f' {(k,l)}')
  txt_output.write("\n")

txt_output.close()