# -*- coding: utf-8 -*-
"""Task_1.A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n9YuZlZ3NFtYNX6lV1tSuJV4_wOUdY3Q
"""

#Task 1.A

txt_input=open('/content/input1a.txt', 'r')
txt_output=open('/content/output1a.txt', 'w')
test_case = (txt_input.readline()).split()

test = int(test_case[0])
sum = int(test_case[1])
#print(test)
#print(sum)

list1=[]
flag1 = False
numbers=(txt_input.readline()).split()
#print(numbers)

for i in range(len(numbers)):
  if flag1 is True:
    break
  else:
    for j in range(i+1, len(numbers)):
      if int(numbers[i]) + int(numbers[j]) == sum:
        list1.append(i+1)
        list1.append(j+1)
        flag1=True
        break

for i in range(len(list1)):
    print(list1[i],end=" ",  file = txt_output)
if list1 == []:
  print(f"Impossible", file=txt_output)
txt_output.close()