# -*- coding: utf-8 -*-
"""Task_2.B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNn9_8Ov67JmzAnUXzd7ZCJndCTbJ3wL
"""

txt_input=open('/content/input2b.txt', 'r')
txt_output=open('/content/output2b.txt', 'w')
test_case1 = (txt_input.readline()).split()
numbers1 = (txt_input.readline()).split()
test_case2 = (txt_input.readline()).split()
numbers2 = (txt_input.readline()).split()

num1=[]
num2=[]
for i in numbers1:
  i2=int(i)
  num1.append(i2)
for j in numbers2:
  j2=int(j)
  num2.append(j2)

i=0
j=0
array=[]

while i < len(num1) and j <len(num2):
  if num1[i] <num2[j]:
        array.append(num1[i])
        i += 1
  else:
      array.append(num2[j])
      j += 1

array= array+num1[i:] +num2[j:]
for i in array:
  print(i, end=" ",  file=txt_output)
txt_output.close()