# -*- coding: utf-8 -*-
"""Task_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ia0Ekt-yXQYxuDXUnzqZOUbOZ5oOA62Z
"""

txt_input=open('/content/input4.txt','r')
txt_output=open('/content/output4.txt','w')
test=txt_input.readline()
numbers=txt_input.readline().split()

num=[]
for i in numbers:
  i2=int(i)
  num.append(i2)
def maximum(array,left,right):
	max1 = 0

	if (left >= right- 2):
		if (array[left] > array[left+ 1]):
			return array[left]
		else:
			return array[left + 1];
	max1 = maximum(array,left+1, right)
	if (array[left] > max1):
		return array[left]
	else:
		return max1
max1= maximum(num, 0, len(num))
print(max1, file = txt_output)
txt_output.close()

#Time complexity O(n)