# -*- coding: utf-8 -*-
"""Task 2(Lab 3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15_2Qf1whGglwDJNgetyoFxNk0iVIyFfy
"""

txt_input=open('/content/input2.txt', 'r')
txt_output=open('/content/output2.txt', 'w')
test_case = (txt_input.readline())

n = int(test_case)
arr=[]
numbers=(txt_input.readline()).split()
print(numbers)
arr1=[]
for i in numbers:
  i2 = int(i)
  arr1.append(i2)

print(arr)

a1 = arr1[0]
a2 = 0

for i in range(1, len(arr1)):
  if arr1[i-1] > a1:
    a1 = arr1[i-1]
  a2 = max(a2, a1+arr1[i]**2)


print(a2, file = txt_output)
txt_output.close()
print(a2)