# -*- coding: utf-8 -*-
"""Task 3(Lab 3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aG0KKnb7v4zDLm4-9wPYFuKOR7q8wrjP
"""

def partition(array, low, high):


    pivot = array[high]
    i = low - 1
    for j in range(low, high):
        if array[j] <= pivot:
            i = i + 1
            (array[i], array[j]) = (array[j], array[i])

    (array[i + 1], array[high]) = (array[high], array[i + 1])

    return i + 1

def quickSort(array, low, high):
    if low < high:

        pi = partition(array, low, high)

        quickSort(array, low, pi - 1)

        quickSort(array, pi + 1, high)


txt_input=open('/content/input3.txt', 'r')
txt_output=open('/content/output3.txt', 'w')
test_case = (txt_input.readline())
test = int(test_case)
numbers=(txt_input.readline()).split()
arr=[]
for i in numbers:
  i2 = int(i)
  arr.append(i2)

n = len(arr)
quickSort(arr, 0, n - 1)
for i in arr:
  print(i,end=" ", file = txt_output)
txt_output.close()