# -*- coding: utf-8 -*-
"""Task 4(Lab 3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Phjmk5XJ6txgI82gWFotW05A5x1wRFZ2
"""

def smallest(arr, k):
    pi = arr[-1]
    arr1 = []
    arr2 = []

    for i in range(len(arr)-1):
        if arr[i] < pi:
            arr1.append(arr[i])
        else:
            arr2.append(arr[i])

    if len(arr1) == k-1:
        return pi
    elif len(arr1) >= k:
        return smallest(arr1, k)
    else:
        return smallest(arr2, k-(len(arr1)+1))

input4 = open(file="/content/input4.txt", mode='r')
output4 = open(file="/content/output4.txt", mode='w')
n = int(input4.readline().strip("\n"))
a = [int(i) for i in input4.readline().strip("\n").split()]
smallest_value = smallest(a, 3)
new1 = int(input4.readline().strip("\n"))


for i in range(new1):
  k = int(input4.readline().strip("\n"))
  kth_smallest = smallest(a, k)
  output4.write(f"{kth_smallest}\n")

output4.close()