# -*- coding: utf-8 -*-
"""Lab 7 Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q2k7HURpw-HcgFIJeyh1QEEyzcs7FF6E
"""

def maxtask(M, time):
  time.sort(key=lambda x: x[1])
  task_done = 0
  assigned = [0] * M

  for i in time:
      start_time, end_time = i
      people = -1
      for i in range(M):
          if assigned[i] <= start_time:
              people = i
              break
      if people != -1:
          assigned[people] = end_time
          task_done += 1
  return task_done

with open("/content/input2.txt", "r") as txt_input, open("/content/output2.txt", "w") as txt_output:
  N, M = map(int, txt_input.readline().split())
  time = []
  for i in range(N):
      start, end = map(int, txt_input.readline().split())
      time.append((start, end))
  total_task = maxtask(M, time)
  print(total_task, file = txt_output)

txt_output.close()